name: 2. Add Identifiers
run-name: Add Identifiers (${{ github.ref_name }})
on:
  workflow_dispatch:

jobs:
  skip:
    name: Add Identifiers
    runs-on: ubuntu-latest
    steps:
      - name: Skip Add Identifiers
        run: echo "Skipping Add Identifiers as secrets are not provided."
