name: 4. Build Trio
run-name: Build Trio (${{ github.ref_name }})
on:
  workflow_dispatch:

jobs:
  skip:
    name: Build Trio
    runs-on: ubuntu-latest
    steps:
      - name: Skip Build Trio
        run: echo "Skipping Build Trio as secrets are not provided."
