name: 3. Create Certificates
run-name: Create Certificates (${{ github.ref_name }})
on:
  workflow_dispatch:

jobs:
  skip:
    name: Create Certificates
    runs-on: ubuntu-latest
    steps:
      - name: Skip Create Certificates
        run: echo "Skipping Create Certificates as secrets are not provided."
